<div class="tech_g_del"></div>
<div class="technology">
	<div class="tech_menu">
		<h1 style="margin-bottom: 20px;">Контакты</h1>
		<div class="tech_menu_del"></div>
	</div>
	<div class="contacts_left">
	</div>

	<div class="technology_right" style="margin-left: 40px; width: 700px;">
		<h1>ООО "Лайт Гласс"</h1>
		<h1 style="margin-top: 30px;">Директор</h1>
		<p style="margin-bottom: 30px;"> Гогенко Василий Анатольевич</p>
		<a href="mailto:v.gogenko@light-glass.ru" style="color: #168ed3; text-decoration: none;">v.gogenko@light-glass.ru</a><br>
		<p style="margin: 5px 0;">8 (938) 107 29 20</p>
		<p>
			ИНН 		<span style="color: #168ed3; margin-left: 20px;">6154125466</span><br>
			КПП 		<span style="color: #168ed3; margin-left: 20px;">615401001</span><br>
			ОГРН 		<span style="color: #168ed3; margin-left: 10px;">1126154008056</span><br>
		</p>
		<h1>Юридический адрес:</h1>
		<p style="margin: 10px 0;">
			347910 Ростовская область, г.Таганрог,<br>
			ул.Котлостроительная, д.37, корп. «В», оф.220
		</p>
		<h1>Тел./факс:</h1>
		<p style="font-weight: bold;">
		р/cч 	<span style="color: #168ed3; margin-left: 20px;font-weight: normal;">№40702810801000005663</span> 	<span style="margin-left: 30px;font-weight: normal;">в Южном филиале ОАО «Промсвязьбанк»</span><br>
		к/сч 	<span style="color: #168ed3; margin-left: 20px;font-weight: normal;">№30101810100000000715</span><br>
		БИК 	<span style="color: #168ed3; margin-left: 20px;font-weight: normal;">041806715</span><br><br><br>

			<a href="mailto:info@adoorservice.ru" style="color: #168ed3; text-decoration: none;font-weight: normal;">info@adoorservice.ru</a>
		</p>

		<div class="contacts_map"></div>
	</div>
</div>