<div class="galery">
	<div class="gal_img">
		<div id="gal_m_1" class="gal_m_i" style="background: url('../img/gal_menu_1.png') no-repeat; width: 621px; height: 252px; margin:200px 0 0 122px;"></div>
		<div id="gal_m_2" class="gal_m_i" style="background: url('../img/gal_menu_2.png') no-repeat; width: 624px; height: 249px; margin:120px 0 0 0;"></div>
		<div id="gal_m_3" class="gal_m_i" style="background: url('../img/gal_menu_3.png') no-repeat; width: 626px; height: 258px; margin:190px 0 0 130px;"></div>
		<div id="gal_m_4" class="gal_m_i" style="background: url('../img/gal_menu_4.png') no-repeat; width: 625px; height: 249px; margin:20px 0 0 -40px;"></div>
		<div id="gal_m_5" class="gal_m_i" style="background: url('../img/gal_menu_5.png') no-repeat; width: 625px; height: 250px; margin:200px 0 0 10px;"></div>
		<div id="gal_m_6" class="gal_m_i" style="background: url('../img/gal_menu_6.png') no-repeat; width: 622px; height: 247px; margin:0 0 0 40px;"></div>
		<div id="gal_m_7" class="gal_m_i" style="background: url('../img/gal_menu_7.png') no-repeat; width: 604px; height: 247px; margin:10px 0 0 150px;"></div>
		<div id="gal_m_8" class="gal_m_i" style="background: url('../img/gal_menu_8.png') no-repeat; width: 616px; height: 247px; margin:80px 0 0 250px;"></div>
	</div>
	<div class="gal_menu">
		<ol>
			<li><a onmouseover="gal_show(1);" onmouseout="gal_hide(1);">Входные группы</a></li>
			<li><a onmouseover="gal_show(2);" onmouseout="gal_hide(2);">Стеклянные козырьки</a></li>
			<li><a onmouseover="gal_show(3);" onmouseout="gal_hide(3);">Стеклянные двери</a></li>
			<li><a onmouseover="gal_show(4);" onmouseout="gal_hide(4);">Стеклянные шахты лифтов</a></li>
			<li><a onmouseover="gal_show(5);" onmouseout="gal_hide(5);">Ограждения эскалаторов</a></li>
			<li><a onmouseover="gal_show(6);" onmouseout="gal_hide(6);">Фасады</a></li>
			<li><a onmouseover="gal_show(7);" onmouseout="gal_hide(7);">Стеклянные перегородки</a></li>
			<li><a onmouseover="gal_show(8);" onmouseout="gal_hide(8);">Ограждения из стекла</a></li>
		</ol>
	</div>
</div>

<div class="main_center">
	<div class="o_kompanii">
		<h1>О компании</h1>
		<div class="del_v_okom"></div>
		<p>В современном интенсивно-развивающемся строительном рынке весомую часть занимает продукция из стекла. Торговые центры, офисы, кинотеатры, спортивные и учебные учреждения, а так же частное строительство – все эти отрасли применяют продукцию из стекла. Современные технологии предоставляют практически невообразимые возможности применения стекла, компания «Light Glass» поможет реализовать ваши самые смелые проекты и рационально использовать все технические возможности. На сегодняшний день мы можем смело заменять стандартные кирпичные и бетонные стены конструкциями из стекла. Для создания прочности и безопасности мы применяем закалённое стекло и триплекс, вы спросите что же делать с теплопотерями? Использование энергосберегающего и мультифункционального стекла позволить существенно сократить эти потери и сохранить ваш бюджет. Мы так же думаем о вашей безопасности, в ассортименте нашей продукции вы найдёте противопожарные конструкции, способные локализовать распространение огня.
			<br><br><b>Мы будем рады помочь вам воплотить в жизнь ваши проекты!</b></p>
	</div>
	<div class="v_del"></div>
	<div class="partners">
		<h1>Наши клиенты</h1>
		<div class="del_v_par"></div>
		<div class="clearfix"></div>
		<a onclick="main_par_b(1);" style='width: 15px; height: 15px; background: url("../img/main_par_arrow_left.png") no-repeat; position: absolute; cursor: pointer;'></a>
		<a onclick="main_par_b(2);" style='width: 15px; height: 15px; background: url("../img/main_par_arrow_right.png") no-repeat; position: absolute; margin-left: 17px; cursor: pointer;'></a>
		<?php
		foreach ($oProjects as $key => $projects) {
			?>
			<div id="par_logo_<?=$key+1?>" class="par_logo" style='<?php if($key != 0){echo "display: none;";} ?> background: url("../img/<?=$projects['logo'] ?>") no-repeat;'></div>
			<div id="par_id_<?=$key+1?>" class="par_text" style="<?php if($key != 0){echo 'display: none;';} ?>">
				<p><span style="color: #87ceeb;"><?=$projects['title'] ?></span></p>
				<p><?=$projects['desc_k'] ?></p>
			</div>
		<?php } ?>



	</div>
</div>