<div class="tech_g_del"></div>
<div class="technology">
	<div class="tech_menu">
		<h1 style="height: 30px;">Вакансии</h1>
		<h2 style="margin-left: 200px;">Должность и обязанности</h2>

		<div class="tech_menu_del"></div>
	</div>
	<div class="jobs_left">
	</div>

	<div class="jobs_right">
		<?php
			foreach($data as $job) {
				echo '<ul>';
					echo '<li>';
						echo "<h1>{$job->title}</h1>";
						echo "<p>{$job->desc}</p>";
						if(isset($job->salary) && ($job->salary != '')) {
							echo "<h2>Уровень зарплаты</h2>";
							echo "<p>{$job->salary}</p>";
						}
					echo '</li>';
				echo '</ul>';
				echo '<ul class="right_right_jobs">';
					if(isset($job->requirements) && ($job->requirements != '')) {
						$aReq = explode(';',$job->requirements);
						echo "<h1>Требования</h1>";
						echo '<ul>';
							foreach($aReq as $req) {
								echo "<li> - {$req}</li>";
							}
						echo '</ul>';
					}
					if(isset($job->qualities) && ($job->qualities != '')) {
						echo '<h1>Личные качества</h1>';
							echo "<p>{$job->qualities}</p>";
					}
					if(isset($job->terms) && ($job->terms != '')) {
						$aTerms = explode(';',$job->terms);
						echo "<h1>Условия</h1>";
						echo '<ul>';
						foreach($aTerms as $term) {
							echo "<li> - {$term}</li>";
						}
						echo '</ul>';
					}
				echo '</ul>';
				echo '<div class="del_jobs"></div>';
			}
		?>
	</div>
</div>