<div class="tech_g_del"></div>
<div class="technology">
	<div class="tech_menu">
		<h1>Технологии и услуги</h1>
		<ul class="project_menu_items">
			<div class="project_arrow"></div><a href="/technology">Вернуться к списку</a>
		</ul>
		<div class="tech_menu_del"></div>
	</div>
	<div class="technology_left">
	</div>

	<div class="technology_right project_item">
		<h1>Проект для компании "<span style="color: #ff9c00;">Money Honey</span>"</h1>
		<div style="width: 600px;">
			<p>Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта. Описание текущего проекта.
			</p>
		</div>
		<div class="tech_undertext_del"></div>
		<ul class="tech_projects prj_img">
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
			<li class="project_imgs"></li>
		</ul>
	</div>
</div>