<div class="tech_g_del"></div>
<div class="technology">
	<div class="tech_menu">
		<h1>Технологии и услуги</h1>
		<ul class="project_menu_items">
			<div class="project_arrow"></div><a href="/technology">Вернуться к списку</a>
		</ul>
		<div class="tech_menu_del"></div>
	</div>
	<div class="technology_left">
	</div>

	<div class="technology_right project_item">
		<h1>Проект для компании "<span style="color: #ff9c00;"><?=$title?></span>"</h1>
		<div style="width: 600px;">
			<p><?=$desc?></p>
		</div>
		<div class="tech_undertext_del"></div>
		<ul class="tech_projects prj_img">
			<?php
				foreach($img as $i) {
					echo "<li class=\"project_imgs\"><img width=\"164\" height=\"164\" src=\"/img/$i\"></li>";
				}
			?>
		</ul>
	</div>
</div>