<div class="tech_g_del"></div>
<div class="technology">
	<div class="tech_menu">
		<h1>Технологии и услуги</h1>
		<ul class="project_menu_items">
			<div class="project_arrow"></div><a href="/technology">Вернуться к списку</a>
		</ul>
		<div class="tech_menu_del"></div>
	</div>
	<div class="technology_left">
	</div>

	<div class="technology_right project_item">
		<h1>Проект для компании "<span style="color: #ff9c00;"><?php if (isset($data['title'])) { echo $data['title']; }?></span>"</h1>
		<div style="width: 600px;">
			<p><?php if (isset($data['desc'])) { echo $data['desc']; }?></p>
		</div>
		<div class="tech_undertext_del"></div>
		<ul class="tech_projects prj_img">
			<?php
				if(isset($data)) {
					for($i = 1; $i <= 10; $i++) {
						if(file_exists($_SERVER['DOCUMENT_ROOT'] . "/img/pro_{$data['id']}_{$i}.jpg")) {
							echo "<li class=\"project_imgs\"><img width=\"164\" height=\"164\" src=\"/img/pro_{$data['id']}_{$i}.jpg\"></li>";
						}
					}
				}
			?>
		</ul>
	</div>
</div>