<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/style.css')?>

		<!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
									  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

	</head>
	<body>
		<div class="main">
			<div class="container">
				<div class="header_up">
					<div class="header_up_left">www.lightglass.ru \ О компании</div>
					<a class="question_arrow"></a>
					<div class="header_up_orange">Написать сообщение, задать вопрос</div>
				</div>
				<ul class="header_main">
					<li class="header_logo"></li>
					<li class="delimer"></li>
					<li class="menu_item"><a href="#" class="current"> О компании</a></li>
					<li class="menu_item"><a href="#">Технологии и услуги</a></li>
					<li class="menu_item"><a href="#">Вакансии</a></li>
					<li class="menu_item"><a href="#">Контакты</a></li>
					<li style="margin-left: 200px;"></li>
					<li class="delimer"></li>
					<li class="social">
						<ul>
							<li>
								<div class="twitter"></div>
							</li>
							<li>
								<div class="facebook"></div>
							</li>
							<li>
								<div class="vkontakte"></div>
							</li>
						</ul>
					</li>
				</ul>
				<?php echo $this->content; ?>
				<div class="footer">
					<ul class="footer_ul">
						<li>
							<a class="list_1">Скачайте презентацию</a>
							<a class="list_2">Прайс-лист</a>
						</li>
						<li class="delimer" style="margin-left: 50px;"></li>
						<li style="margin-left: 50px;">
							<a class="list_1">Партнерам</a>
							<a class="list_2">Специальное предложение</a>
						</li>
						<li class="delimer" style="margin-left: 50px;"></li>
						<li class="delimer" style="margin-left: 430px;"></li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>
