<?php echo $this->doctype(); ?>

<html lang="ru">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('Light-Glass.ru'); ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/style.css')?>

		<!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
									  ->prependFile($this->basePath() . '/js/lightglass.js')
									  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

	</head>
	<body>
		<div class="main">
			<div class="container">
				<div class="header_up">
					<div class="header_up_left">www.lightglass.ru \ О компании</div>
					<a class="question_arrow"></a>
					<div class="header_up_orange">Написать сообщение, задать вопрос</div>
				</div>
				<ul class="header_main">
					<?  $aUrl = parse_url( $_SERVER['REQUEST_URI'] );
					    $sCurrent = ( !empty( $aUrl ) ) ? $aUrl['path'] : '';
					?>
					<li class="header_logo"></li>
					<li class="delimer"></li>
					<li class="menu_item"><a href="/" <?=$sCurrent == '/' ? 'class="current"' : ''?>>О компании</a></li>
					<li class="menu_item"><a href="/technology" <?=$sCurrent == '/technology' ? 'class="current"' : ''?>>Технологии и услуги </a></li>
					<li class="menu_item"><a href="#" <?=$sCurrent == '#' ? 'class="current"' : ''?>>Вакансии</a></li>
					<li class="menu_item"><a href="#" <?=$sCurrent == '#' ? 'class="current"' : ''?>>Контакты</a></li>
					<li style="margin-left: 200px;"></li>
					<li class="delimer"></li>
					<li class="social">
						<ul>
							<li>
								<div class="twitter"></div>
							</li>
							<li>
								<div class="facebook"></div>
							</li>
							<li>
								<div class="vkontakte"></div>
							</li>
						</ul>
					</li>
				</ul>
				<?php echo $this->content; ?>
				<div class="footer">
					<ul class="footer_ul">
						<li>
							<a class="list_1" href="#">Скачайте презентацию</a>
							<a class="list_2" href="#">Прайс-лист</a>
						</li>
						<li class="delimer" style="margin-left: 50px;"></li>
						<li style="margin-left: 50px;">
							<a class="list_1" href="#">Партнерам</a>
							<a class="list_2" href="#">Специальное предложение</a>
						</li>
						<li class="delimer" style="margin-left: 50px;"></li>
						<li class="delimer" style="margin-left: 430px;"></li>
						<li class="social" style="margin: 0;">
							<ul>
								<li style="margin: 0 0 0 10px;">
									<div class="twitter"></div>
								</li>
								<li style="margin: 0 0 0 10px;">
									<div class="facebook"></div>
								</li>
								<li style="margin: 0 0 0 10px;">
									<div class="vkontakte"></div>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<ul class="copyright">
					<li>www.lightglass.ru</li>
					<li style="margin-left: 10px;">Все права защищены!</li>
					<li style="margin-left: 830px;">Сайт разработан студией inoweb</li>
				</ul>
			</div>
		</div>
	</body>
</html>
